force-app/main/default/objects/Mi_moto__c/Mi_moto__c.object-meta.xml
<CustomObject>
    <label>Mi moto</label>
    <nameField>
        <label>Mi moto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mis motos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mi_moto__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <referenceTo>Modelo__c</referenceTo>
    <relationshipLabel>Mis motos</relationshipLabel>
    <relationshipName>Mis_motos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mi_moto__c/fields/Proxima_Revision__c.field-meta.xml
<CustomField>
    <fullName>Proxima_Revision__c</fullName>
    <label>Proxima Revision</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mi_moto__c/fields/Proximo_Cambio_De_Aceite__c.field-meta.xml
<CustomField>
    <fullName>Proximo_Cambio_De_Aceite__c</fullName>
    <label>Proximo Cambio De Aceite</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mi_moto__c/fields/Ultima_Revision__c.field-meta.xml
<CustomField>
    <fullName>Ultima_Revision__c</fullName>
    <label>Ultima Revision</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mi_moto__c/fields/Ultimo_Cambio_De_Aceite__c.field-meta.xml
<CustomField>
    <fullName>Ultimo_Cambio_De_Aceite__c</fullName>
    <label>Ultimo Cambio De Aceite</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Modelo__c/Modelo__c.object-meta.xml
<CustomObject>
    <label>Modelo</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modelo__c/fields/Cilindrada__c.field-meta.xml
<CustomField>
    <fullName>Cilindrada__c</fullName>
    <label>Cilindrada</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Frecuencia_Cambio_Aceite__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia_Cambio_Aceite__c</fullName>
    <label>Frecuencia Cambio Aceite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Frecuencia_Revision__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia_Revision__c</fullName>
    <label>Frecuencia Revision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio</label>
    <precision>16</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Procedencia__c.field-meta.xml
<CustomField>
    <fullName>Procedencia__c</fullName>
    <label>Procedencia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Japonesa</fullName>
            </value>
            <value>
                <fullName>Europea</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MotoTriggerTest.cls
@isTest
private with sharing class MotoTriggerTest {

    @isTest
    static void testInsertTrigger() {
        // GIVEN
        Modelo__c modelo = new Modelo__c(Frecuencia_Revision__c = 365, Frecuencia_Cambio_Aceite__c = 365,  Marca__c = 'Honda', Cilindrada__c = 400, Precio__c = 1000, Procedencia__c = 'China');
        insert modelo;

        Mi_moto__c miMoto1 = new Mi_moto__c(Modelo__c = modelo.Id, Ultima_Revision__c = Date.today(), Ultimo_Cambio_De_Aceite__c = Date.today());

        // WHEN
        Test.startTest();
        insert miMoto1;
        Test.stopTest();

        // THEN
        // Verificar que la próxima revisión y el próximo cambio de aceite se hayan calculado correctamente después de la inserción
        miMoto1 = [SELECT Id, Proxima_Revision__c, Ultima_Revision__c, Ultimo_Cambio_De_Aceite__c, Proximo_Cambio_De_Aceite__c FROM Mi_moto__c WHERE Id = :miMoto1.Id LIMIT 1];

        // Calcular las fechas esperadas
        Date expectedNextRevision = miMoto1.Ultima_Revision__c.addDays(MotoFrecuencia.getDiasRevision(modelo));
        Date expectedNextOilChange = miMoto1.Ultimo_Cambio_De_Aceite__c.addDays(MotoFrecuencia.getDiasCambioAceite(modelo));

        // Verificar que las fechas calculadas sean las esperadas
        System.assertEquals(expectedNextRevision, miMoto1.Proxima_Revision__c, 'La próxima revisión debe ser calculada correctamente');
        System.assertEquals(expectedNextOilChange, miMoto1.Proximo_Cambio_De_Aceite__c, 'El próximo cambio de aceite debe ser calculado correctamente');
    }

    @isTest
static void testUpdateTrigger() {
    // GIVEN
    Modelo__c modelo = new Modelo__c( Frecuencia_Revision__c = 365, Frecuencia_Cambio_Aceite__c = 90, Marca__c = 'Honda', Cilindrada__c = 400, Precio__c = 1000, Procedencia__c = 'China');
    insert modelo;

    Mi_moto__c miMoto = new Mi_moto__c(Modelo__c = modelo.Id, Ultima_Revision__c = Date.today(), Ultimo_Cambio_De_Aceite__c = Date.today());
    insert miMoto;

    // WHEN
    Test.startTest();
    // Actualizar la fecha de última revisión y último cambio de aceite
    miMoto = [SELECT Id, Ultima_Revision__c, Ultimo_Cambio_De_Aceite__c FROM Mi_moto__c WHERE Id = :miMoto.Id LIMIT 1];
    miMoto.Ultima_Revision__c = Date.today().addDays(30);
    miMoto.Ultimo_Cambio_De_Aceite__c = Date.today().addDays(15);
    update miMoto;
    Test.stopTest();

    // THEN
    // Verificar que la próxima revisión y el próximo cambio de aceite se hayan recalculado correctamente después de la actualización
    miMoto = [SELECT Id, Proxima_Revision__c, Proximo_Cambio_De_Aceite__c, Ultima_Revision__c, Ultimo_Cambio_De_Aceite__c FROM Mi_moto__c WHERE Id = :miMoto.Id LIMIT 1];

    // Calcular las fechas esperadas después de la actualización
    Date expectedNextRevision = miMoto.Ultima_Revision__c.addDays(MotoFrecuencia.getDiasRevision(modelo));
    Date expectedNextOilChange = miMoto.Ultimo_Cambio_De_Aceite__c.addDays(MotoFrecuencia.getDiasCambioAceite(modelo));

    // Verificar que las fechas recalculadas sean las esperadas después de la actualización
    System.assertEquals(expectedNextRevision, miMoto.Proxima_Revision__c, 'La próxima revisión debe ser recalculada correctamente después de la actualización');
    System.assertEquals(expectedNextOilChange, miMoto.Proximo_Cambio_De_Aceite__c, 'El próximo cambio de aceite debe ser recalculado correctamente después de la actualización');
}
}