force-app/main/default/objects/Modelo__c/Modelo__c.object-meta.xml
<CustomObject>
    <label>Modelo</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modelo__c/fields/Frecuencia_Cambio_Aceite__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia_Cambio_Aceite__c</fullName>
    <label>Frecuencia Cambio Aceite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Frecuencia_Revision__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia_Revision__c</fullName>
    <label>Frecuencia Revision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MotoFrecuencia.cls
public with sharing class MotoFrecuencia {
   

    public static Integer getDiasRevision(Modelo__c Modelo) {

        Integer frecuenciaInteger = Modelo.Frecuencia_Revision__c.intValue();

        return frecuenciaInteger;

    }


public static Integer getDiasCambioAceite(Modelo__c Modelo) {
    Integer frecuenciaInteger = Modelo.Frecuencia_Cambio_Aceite__c.intValue();

        return frecuenciaInteger;
    }
}