force-app/main/default/objects/Modelo__c/Modelo__c.object-meta.xml
<CustomObject>
    <label>Modelo</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modelo__c/fields/Frecuencia_Cambio_Aceite__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia_Cambio_Aceite__c</fullName>
    <label>Frecuencia Cambio Aceite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Frecuencia_Revision__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia_Revision__c</fullName>
    <label>Frecuencia Revision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MotoFrecuenciaTest.cls
@isTest
private with sharing class MotoFrecuenciaTest {
    
    @isTest 
    static void testGetDiasRevision() {
        // Crea un objeto Modelo__c con frecuencia de revisión de 365 días
        Modelo__c modelo = new Modelo__c(Frecuencia_Revision__c = 365);

        // Llama al método estático de la clase MotoFrecuencia para obtener la frecuencia de revisión
        Integer days = MotoFrecuencia.getDiasRevision(modelo);

        // Define el valor esperado de la frecuencia de revisión
        Integer expectedDays = 365;

        // Verifica que el resultado obtenido sea igual al valor esperado
        System.assertEquals(expectedDays, days, 'La frecuencia de revisión debe ser 365 días');
    }

    @isTest 
    static void getDiasCambioAceite() {
        // Crea un objeto Modelo__c con frecuencia de revisión de 365 días
        Modelo__c modelo = new Modelo__c(Frecuencia_Cambio_Aceite__c = 365);

        // Llama al método estático de la clase MotoFrecuencia para obtener la frecuencia de revisión
        Integer days = MotoFrecuencia.getDiasCambioAceite(modelo);

        // Define el valor esperado de la frecuencia de revisión
        Integer expectedDays = 365;

        // Verifica que el resultado obtenido sea igual al valor esperado
        System.assertEquals(expectedDays, days, 'La frecuencia del cambio de aceite debe ser 365 días');
    }
}