force-app/main/default/objects/Modelo__c/Modelo__c.object-meta.xml
<CustomObject>
    <label>Modelo</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modelo__c/fields/Cilindrada__c.field-meta.xml
<CustomField>
    <fullName>Cilindrada__c</fullName>
    <label>Cilindrada</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio</label>
    <precision>16</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modelo__c/fields/Procedencia__c.field-meta.xml
<CustomField>
    <fullName>Procedencia__c</fullName>
    <label>Procedencia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Japonesa</fullName>
            </value>
            <value>
                <fullName>Europea</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MotoServiceTest.cls
@isTest
private class MotoServiceTest {

    @isTest
    static void testGetFilteredModelos() {
        // GIVEN
        // Crea algunos modelos de prueba
        Modelo__c modelo1 = new Modelo__c(Name = 'Modelo 1', Precio__c = 1000, Cilindrada__c = 400, Marca__c = 'Marca A', Procedencia__c = 'China');
        Modelo__c modelo2 = new Modelo__c(Name = 'Modelo 2', Precio__c = 1500, Cilindrada__c = 400, Marca__c = 'Marca B', Procedencia__c = 'China');
        Modelo__c modelo3 = new Modelo__c(Name = 'Otro Modelo', Precio__c = 1200, Cilindrada__c = 400, Marca__c = 'Marca A', Procedencia__c = 'China');
        insert new List<Modelo__c>{modelo1, modelo2, modelo3};

        // WHEN
        Test.startTest();
        // Llama al método getFilteredModelos con el texto de búsqueda 'Modelo'
        List<Modelo__c> modelosFiltrados = MotoService.getFilteredModelos('Modelo');
        Test.stopTest();

        // THEN
        // Verifica que los modelos devueltos contengan 'Modelo' en el nombre
        for (Modelo__c modelo : modelosFiltrados) {
            System.assert(modelo.Name.contains('Modelo'), 'El nombre del modelo debe contener "Modelo"');
        }
    }
}